plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Applications/MyCity /MyCity/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "expo export -p web"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]